const ENTITY_REGEX = /^[a-z_][a-z0-9_-]*$/;

const ENTITY_RESRVED_WORDS = [
  'all',
  'analyse',
  'analyze',
  'and',
  'any',
  'array',
  'as',
  'asc',
  'asymmetric',
  'both',
  'case',
  'cast',
  'check',
  'collate',
  'column',
  'constraint',
  'create',
  'current_catalog',
  'current_date',
  'current_role',
  'current_time',
  'current_timestamp',
  'current_user',
  'default',
  'deferrable',
  'desc',
  'distinct',
  'do',
  'else',
  'end',
  'except',
  'false',
  'fetch',
  'for',
  'foreign',
  'from',
  'grant',
  'group',
  'having',
  'in',
  'initially',
  'intersect',
  'into',
  'lateral',
  'leading',
  'limit',
  'localtime',
  'localtimestamp',
  'not',
  'null',
  'offset',
  'on',
  'only',
  'or',
  'order',
  'placing',
  'primary',
  'references',
  'returning',
  'select',
  'session_user',
  'some',
  'symmetric',
  'table',
  'then',
  'to',
  'trailing',
  'true',
  'union',
  'unique',
  'user',
  'using',
  'variadic',
  'when',
  'where',
  'window',
  'with',
];

export const validateEntityName = (name: string) => {
  if (ENTITY_RESRVED_WORDS.includes(name)) {
    throw new Error(`Entity name "${name}" is a reserved keyword`);
  }
  if (!ENTITY_REGEX.test(name)) {
    throw new Error(
      `Entity name "${name}" is not valid, must start with a letter or underscore and contain only lowercase letters, numbers, hyphens and underscores`,
    );
  }
};
